// layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/navigation";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/ReactToastify.min.css"; 
import BudgetContextProvider from "@/lib/store/budgetContext";
import AuthContextProvider from "@/lib/store/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BudgetBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <BudgetContextProvider>
            <ToastContainer/>
              <Nav />
              {children}
          </BudgetContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
